################ MST MRD TRAVIS CI ################
language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=drone_control/
    
install:
    - pip install -U platformio
    - wget https://github.com/adafruit/Adafruit_L3GD20/archive/1.0.0.zip -O /tmp/gyro_source.zip
    - unzip /tmp/gyro_source.zip -d /tmp/

script:
    - chmod +x prep.sh
    - ./prep.sh
    - platformio ci --lib="/tmp/Adafruit_L3GD20-1.0.0" --board=megaatmega2560
